---
- ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    openjdk_app: jre
- name: Downloading {{ teampostgresql_url }} to {{ teampostgresql_tmp_zip }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ teampostgresql_url }}'
    dest: '{{ teampostgresql_tmp_zip }}'
    mode: '644'

- name: Unzip {{ teampostgresql_tmp_zip }}...
  become: true
  become_user: root
  ansible.builtin.unarchive:
    src: '{{ teampostgresql_tmp_zip }}'
    dest: '{{ teampostgresql_parent_install_dir }}'
    creates: '{{ teampostgresql_install_dir }}'

- name: Templatize...
  become: true
  become_user: root
  with_items:
    - f: teampostgresql.sh
      d: /etc/profile.d
      m: '644'
    - f: teampostgresql-run.sh
      d: '{{ teampostgresql_install_dir }}'
      m: '755'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
